on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/hello-devops:latest
            ghcr.io/${{ github.repository_owner }}/hello-devops:${{ github.sha }}

      - name: Smoke test container
        run: |
          docker run -d -p 5000:5000 --name web ghcr.io/${{ github.repository_owner }}/hello-devops:latest
          sleep 3
          curl -fsS http://127.0.0.1:5000 | grep -i "hello"
          docker logs web
          docker rm -f web
